apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cos-fleetshard-operator-debezium
  name: cos-fleetshard-operator-debezium
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: cos-fleetshard-operator-debezium
  type: ClusterIP
